import os
import json
import uuid
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def _read_log():
    """Read the full audit log from disk. Returns a list of entries."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def write_log(entry):
    """Append a single structured entry to the audit log."""
    entries = _read_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def get_log(limit=20):
    """Return the most recent `limit` audit log entries, newest first."""
    entries = _read_log()
    return list(reversed(entries))[:limit]


def find_log_entry(content_id):
    """Find a single audit log entry by content_id. Returns None if not found."""
    entries = _read_log()
    for entry in entries:
        if entry.get("content_id") == content_id:
            return entry
    return None


def update_log_entry(content_id, updates):
    """Update fields on an existing log entry, identified by content_id."""
    entries = _read_log()
    found = False
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            found = True
            break
    if found:
        with open(LOG_FILE, "w") as f:
            json.dump(entries, f, indent=2)
    return found


# ---------------------------------------------------------------------------
# Signal 1: Groq LLM classifier (semantic)
# ---------------------------------------------------------------------------

def groq_signal(text):
    """
    Sends text to Groq's llama-3.3-70b-versatile model and asks it to
    assess AI-likelihood. Returns a float between 0.0 and 1.0.

    0.0 = confident this is human-written
    1.0 = confident this is AI-generated
    """
    prompt = f"""You are a text-provenance classifier. Analyze the following text and
estimate the probability that it was generated by an AI language model
rather than written by a human.

Consider: phrasing register, tonal consistency, structural predictability,
vocabulary choices, and overall coherence patterns typical of AI writing.

Respond with ONLY a JSON object in this exact format, nothing else:
{{"ai_likelihood": 0.0}}

The ai_likelihood value must be a float between 0.0 and 1.0.

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"
"""

    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=50,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if the model wraps its JSON output
        raw = raw.replace("```json", "").replace("```", "").strip()

        parsed = json.loads(raw)
        score = float(parsed.get("ai_likelihood", 0.5))
        return max(0.0, min(1.0, score))  # clamp to [0, 1]

    except Exception as e:
        # If the LLM call or parsing fails, fall back to a neutral score
        # rather than crashing the request. Log this for debugging.
        print(f"[groq_signal] Error: {e}")
        return 0.5


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Signal 1 — only signal wired in for this milestone
    llm_score = groq_signal(text)

    # Placeholders — wired in properly in Milestone 4
    confidence = llm_score
    attribution = "likely_ai" if llm_score >= 0.65 else (
        "likely_human" if llm_score < 0.35 else "uncertain"
    )
    label = "placeholder - label generator added in Milestone 5"

    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": round(confidence, 3),
        "llm_score": round(llm_score, 3),
        "stylometric_score": None,  # added in Milestone 4
        "status": "classified",
    }
    write_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": round(confidence, 3),
        "label": label,
    })


@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})


if __name__ == "__main__":
    app.run(debug=True, port=5000)