import os
import json
import uuid
import math
import string
import re
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiting
# 10 per minute: prevents automated flooding (a real writer submits maybe
# once or twice in a sitting, not 10 times per minute)
# 100 per day: generous for legitimate use, but makes bulk scraping costly
# ---------------------------------------------------------------------------
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def _read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def write_log(entry):
    entries = _read_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def get_log(limit=20):
    entries = _read_log()
    return list(reversed(entries))[:limit]


def find_log_entry(content_id):
    entries = _read_log()
    for entry in entries:
        if entry.get("content_id") == content_id:
            return entry
    return None


def update_log_entry(content_id, updates):
    entries = _read_log()
    found = False
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            found = True
            break
    if found:
        with open(LOG_FILE, "w") as f:
            json.dump(entries, f, indent=2)
    return found


# ---------------------------------------------------------------------------
# Signal 1: Groq LLM classifier (semantic)
# ---------------------------------------------------------------------------

def groq_signal(text):
    prompt = f"""You are a text-provenance classifier. Analyze the following text and
estimate the probability that it was generated by an AI language model
rather than written by a human.

Consider: phrasing register, tonal consistency, structural predictability,
vocabulary choices, and overall coherence patterns typical of AI writing.

Respond with ONLY a JSON object in this exact format, nothing else:
{{"ai_likelihood": 0.0}}

The ai_likelihood value must be a float between 0.0 and 1.0.

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"
"""
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=50,
        )
        raw = response.choices[0].message.content.strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)
        score = float(parsed.get("ai_likelihood", 0.5))
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"[groq_signal] Error: {e}")
        return 0.5


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (structural)
# ---------------------------------------------------------------------------

def _sentence_length_variance_score(sentences):
    if len(sentences) < 2:
        return 0.5
    lengths = [len(s.split()) for s in sentences if s.strip()]
    if len(lengths) < 2:
        return 0.5
    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    score = max(0.0, 1.0 - (std_dev / 10.0))
    return round(min(1.0, score), 4)


def _type_token_ratio_score(words):
    if len(words) < 5:
        return 0.5
    words_lower = [w.lower().strip(string.punctuation) for w in words if w.strip()]
    total = len(words_lower)
    unique = len(set(words_lower))
    ttr = unique / total
    score = 1.0 - ttr
    return round(max(0.0, min(1.0, score)), 4)


def _punctuation_density_score(text):
    if len(text) < 10:
        return 0.5
    expressive = set("!?—…;:()")
    expressive_count = sum(1 for ch in text if ch in expressive)
    density = expressive_count / len(text)
    score = max(0.0, 1.0 - (density / 0.02))
    return round(min(1.0, score), 4)


def stylometric_signal(text):
    words = text.split()
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    low_data = len(words) < 30 or len(sentences) < 2
    if low_data:
        return 0.5, True
    s1 = _sentence_length_variance_score(sentences)
    s2 = _type_token_ratio_score(words)
    s3 = _punctuation_density_score(text)
    combined = (s1 + s2 + s3) / 3.0
    return round(combined, 4), False


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def score_confidence(llm_score, stylometric_score):
    combined = round((0.6 * llm_score) + (0.4 * stylometric_score), 3)
    if combined >= 0.65:
        attribution = "likely_ai"
    elif combined < 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    return combined, attribution


# ---------------------------------------------------------------------------
# Transparency label generator
# ---------------------------------------------------------------------------

def generate_label(confidence, attribution, low_data=False):
    """
    Maps confidence score + attribution to one of three transparency label
    variants. Percentages shown always reflect the direction of the verdict.
    """
    warning = "\n\n⚠️ Note: This submission was too short for reliable structural analysis. Results may be less accurate." if low_data else ""

    if attribution == "likely_ai":
        pct = round(confidence * 100)
        return (
            f"⚠️ AI-Generated Content Likely\n\n"
            f"Our system has analyzed this submission and found strong indicators "
            f"that it may have been generated with AI assistance (confidence: {pct}%).\n\n"
            f"This label does not mean the content has no value — it's here to help "
            f"readers understand how it was created. If you are the creator and believe "
            f"this is incorrect, you can submit an appeal."
            f"{warning}"
        )
    elif attribution == "likely_human":
        pct = round((1 - confidence) * 100)
        return (
            f"✅ Likely Human-Written\n\n"
            f"Our system found strong indicators that this content was written by a "
            f"person (confidence: {pct}%).\n\n"
            f"This label reflects our best analysis and is not a guarantee. Our "
            f"detection system is not perfect."
            f"{warning}"
        )
    else:  # uncertain
        pct = round(confidence * 100)
        return (
            f"🔍 Authorship Uncertain\n\n"
            f"Our system analyzed this submission but could not confidently determine "
            f"whether it was written by a person or generated with AI assistance "
            f"(confidence: {pct}%).\n\n"
            f"Some writing styles, non-native English, or formal prose can be difficult "
            f"to classify. If you are the creator, you may submit an appeal to add context."
            f"{warning}"
        )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    llm_score = groq_signal(text)
    stylo_score, low_data = stylometric_signal(text)
    confidence, attribution = score_confidence(llm_score, stylo_score)
    label = generate_label(confidence, attribution, low_data)

    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 3),
        "stylometric_score": stylo_score,
        "low_data_warning": low_data,
        "status": "classified",
    }
    write_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "signals": {
            "llm_score": round(llm_score, 3),
            "stylometric_score": stylo_score,
            "low_data_warning": low_data,
        },
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id", "").strip()
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not creator_reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    entry = find_log_entry(content_id)
    if not entry:
        return jsonify({"error": f"No submission found with content_id: {content_id}"}), 404

    if entry.get("status") == "under_review":
        return jsonify({
            "content_id": content_id,
            "status": "under_review",
            "message": "An appeal for this submission is already under review.",
        }), 200

    appeal_timestamp = datetime.now(timezone.utc).isoformat()
    update_log_entry(content_id, {
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
        "appeal_timestamp": appeal_timestamp,
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and will be reviewed. Thank you for providing context.",
        "appeal_timestamp": appeal_timestamp,
    })


@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})


if __name__ == "__main__":
    app.run(debug=True, port=5000)